## Chapter 2. 파이썬 기초와 넘파이 라이브러리

### 2.1. 변수와 자료형

#### 2.1.1. 변수

#### 2.1.2. 정수

#### 2.1.3. 실수

In [1]:
# 코드 2-1. 실수의 출력
13.01 # 부동 소수점으로 출력하는 것은 아니다.

13.01

#### 2.1.4. 문자열

In [2]:
# 코드 2-2. 문자열의 연결
'김' + '판다'

'김판다'

In [3]:
# 코드 2-3. 문자열의 인덱싱
a = '김판다'
a[0] # 첫 번째 문자열을 반환한다

'김'

In [4]:
# 코드 2-4. len 함수로 문자열의 길이 반환
len(a) # 변수 a인 문자열 '김판다'의 길이를 반환한다

3

In [5]:
# 코드 2-5. 문자열 포매팅(f-string 기법)
a = '김판다'
b = '판다스'
f'{a} 강사와 함께 {b}를 배웁시다'

'김판다 강사와 함께 판다스를 배웁시다'

In [6]:
# 코드 2-6. 문자열 포매팅(format 함수)
'{} 강사와 함께 {}를 배웁시다'.format(a, b)

'김판다 강사와 함께 판다스를 배웁시다'

In [7]:
# 코드 2-7. 문자열 포매팅 대신 문자열 연결을 사용
a + ' 강사와 함께 ' + b + '를 배웁시다'

'김판다 강사와 함께 판다스를 배웁시다'

#### 2.1.5. 불

In [8]:
# 코드 2-8. 불(bool) 자료형의 산술 연산
True + True + False

2

In [9]:
# 코드 2-9. 불(bool) 자료형의 논리 연산
True & True & False # 모두 True인 것이 아니므로 False를 반환한다.

False

#### 2.1.6. 리스트

In [10]:
# 코드 2-10. 리스트의 생성
[1, 2, 3]

[1, 2, 3]

In [11]:
# 코드 2-11. type 함수로 자료형 확인
type([1, 2, 3])

list

In [12]:
# 코드 2-12. 리스트의 연결
[1, 2, 3] + [4, 5]

[1, 2, 3, 4, 5]

In [13]:
# 코드 2-13. 리스트의 반복
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [14]:
# 코드 2-14. 리스트의 인덱싱
a = [1, 2, 3]
a[0] # 리스트의 첫 번째 원소를 추출한다.

1

In [15]:
# 코드 2-15. 리스트의 길이 반환
len(a)

3

#### 2.1.7. 튜플

In [16]:
# 코드 2-16. 튜플의 생성
(1, 2, 3)

(1, 2, 3)

In [17]:
# 코드 2-17. type 함수로 튜플의 자료형 확인
type((1, 2, 3))

tuple

In [18]:
# 코드 2-18. 튜플은 괄호를 생략할 수도 있다.
a = 1, 2
type(a)

tuple

In [19]:
# 코드 2-19. 튜플을 이용해 복수의 변수 한 번에 지정하기
b, c = 1, 2
print(b)
print(c)

1
2


#### 2.1.8. 딕셔너리

In [20]:
# 코드 2-20. 딕셔너리 생성
{'가': 1, '나': 2}

{'가': 1, '나': 2}

In [21]:
# 코드 2-21. 딕셔너리의 인덱싱
a = {'가': 1, '나': 2}
a['가']

1

In [22]:
# 코드 2-22. 딕셔너리의 원소 수정하기
a = {'가': 1, '나': 2}
a['가'] = 3
a

{'가': 3, '나': 2}

In [23]:
# 코드 2-23. 딕셔너리에 원소 추가하기
a = {'가': 1, '나': 2}
a['다'] = 3 # '다'는 a에 존재하지 않는 키이다.
a

{'가': 1, '나': 2, '다': 3}

### 2.2. 제어문과 함수

#### 2.2.1. 제어문

In [24]:
# 코드 2-24. 반복문 수행하기
for i in ['a', 1, 3.1]:
    print(type(i))

<class 'str'>
<class 'int'>
<class 'float'>


In [25]:
# 코드 2-25. 반복문을 사용하지 않고 코드 2-24를 수행하는 코드
print(type('a'))
print(type(1))
print(type(3.1))

<class 'str'>
<class 'int'>
<class 'float'>


#### 2.2.2. 함수

In [26]:
# 코드 2-26. 함수 정의하기
def add_one(x):
    return x + 1

# 생성한 add_one 함수를 호출해 인수 2를 입력하기
add_one(2)

3

### 2.3. 클래스와 객체, 라이브러리

#### 2.3.1. 클래스와 객체

#### 2.3.2. 라이브러리

In [27]:
# 코드 2-27. 판다스 라이브러리 불러오기
import pandas as pd

In [28]:
# 코드 2-28. 판다스 라이브러리의 버전 확인하기
pd.__version__

'2.1.4'

판다스 라이브러리를 별도로 설치해야 하거나, 버전 차이로 인해 판다스 2.1.4 버전으로 업그레이드 또는 다운그레이드를 원하는 독자들은 아래 코드를 실행하자.

```python
!pip install pandas==2.1.4
```

#### 2.3.3. 넘파이 라이브러리

In [29]:
# 코드 2-29. 넘파이 라이브러리 불러오기
import numpy as np

In [30]:
# 코드 2-30. 넘파이 라이브러리의 버전 확인하기
np.__version__

'1.26.4'

In [31]:
# 코드 2-31. 넘파이의 어레이 클래스 생성하기
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# 코드 2-32. 어레이의 벡터화 연산
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [33]:
# 코드 2-33. 어레이의 벡터화 연산(비교 연산)
a > 2

array([[False, False,  True],
       [ True,  True,  True]])